Repository PlaceOS/.github, pull requests merged in 2022-02, with the labels that each got.

#34 feat: implement centralised build dev image
  .github/workflows/build-dev-image.yml
Labels: focus: devops, type: refactor

#35 fix(build-dev-image): add some args for non-standard options
  .github/workflows/build-dev-image.yml
Labels: type: bug, type: maintenance

#37 fix(docker): upgrade apk to support version of APKINDEX.tar.gz in edge
  Dockerfile
Labels: type: bug

#40 feat: changelogs
  .github/workflows/changelog.yml
  .github/workflows/shard-version.yml
  .github/workflows/validate-pr-title.yml
Labels: focus: devops, type: new feature
