Repository PlaceOS/.github, pull requests merged in 2022-03, with the labels that each got.

#39 feat(publish-crystal-docs): add action to generate crystal docs
  .github/workflows/publish-crystal-docs.yml
Labels: focus: devops, type: enhancement

#50 fix(todos): allow initial commit to be set
  .github/workflows/containerised-test.yml
Labels: focus: devops, type: bug

#53 fix(build): Fix Spec container builds
  Dockerfile
Labels: type: bug

#54 ci(build-spec-containers): only run on main branch
  .github/workflows/build-spec-containers.yml
Labels: type: maintenance

#55 Fix(kcov): make kcov work?
  Dockerfile
Labels: focus: devops, type: bug

#57 fix(build-spec-containers): publish when branch is main
  .github/workflows/build-spec-containers.yml
Labels: focus: devops, type: bug
